"""
MEOK LAW — region-aware AI governance, built on the REAL CSOAI crosswalks.

The pitch: any agent, humanoid, robotics company, or business connects to MEOK LAW
and gets three honest answers —
  1. "Which rules apply to me, here?"      -> applicable(region, entity)
  2. "What happens when I cross a border?" -> crosswalk(from_region, to_region)
  3. "Prove I'm governed + tracked."       -> register(entity) + agents()

How it actually works (no magic): the CSOAI 52-Article Partnership Charter is the HUB.
Every framework we cover (EU AI Act, NIST AI RMF, UK, Singapore, OECD, UNESCO, …) is
crosswalked to charter articles. So an agent governed to the charter (via the Sovereign
Gate + care bond) can be MAPPED to whichever framework a region demands — and when it
crosses regions, we re-map the SAME charter obligations to the destination's framework.
That mapping is the "AI social contract" it carries across borders.

Data: meok_one/data/law_bundle.json  (generated by tools/build_law_bundle.py from the
real crosswalk-json). Coverage today: 12 framework crosswalks + 4 domain crosswalk MCPs.
This is informational governance mapping, NOT legal advice.

Stdlib only. Audit via meok_one.sigil (hash-chained). Authored by Claude (Opus 4.8).
"""
import json
import os
import time

_HERE = os.path.dirname(os.path.abspath(__file__))
# law_bundle.json is SOURCE data (generated from the crosswalks) — lives beside law.py,
# next to characters.json. The data/ dir is runtime-only (gitignored), so the registry
# of live registrations goes there.
_BUNDLE_PATH = os.path.join(_HERE, "law_bundle.json")
_AGENTS_LOG = os.path.join(_HERE, "data", "law_agents.jsonl")

_DISCLAIMER = ("Informational governance mapping, not legal advice. Confirm with "
               "qualified counsel for your jurisdiction and use-case.")

_ENTITIES = {
    "ai_agent": "Software AI agent",
    "humanoid": "Humanoid / physical robot",
    "robotics_company": "Robotics company (builder)",
    "business": "Business deploying AI",
}

_bundle = None


def _load() -> dict:
    global _bundle
    if _bundle is None:
        with open(_BUNDLE_PATH) as f:
            _bundle = json.load(f)
    return _bundle


def _fw(fid: str) -> dict:
    return _load()["frameworks"].get(fid, {})


def _region(rid: str) -> dict:
    rid = (rid or "GLOBAL").upper()
    regions = _load()["regions"]
    return regions.get(rid, regions["GLOBAL"]), (rid if rid in regions else "GLOBAL")


def _primary_fw(rid: str):
    """The representative framework for a region: its binding law if any, else top advisory."""
    r, _ = _region(rid)
    fids = (r.get("binding") or []) + (r.get("advisory") or [])
    return fids[0] if fids else None


# ----------------------------------------------------------------------------- overview
def overview() -> dict:
    """The MEOK LAW capability map — frameworks, regions, MCPs, honest coverage."""
    b = _load()
    fws = [{"id": f["id"], "name": f["name"], "region": f["region"], "kind": f["kind"],
            "binding": f["binding"], "cite": f["cite"], "mappings": f["total_mappings"],
            "topics": f["topics"]} for f in b["frameworks"].values()]
    fws.sort(key=lambda x: (not x["binding"], x["region"]))
    regions = [{"id": rid, "label": r["label"],
                "binding": [_fw(x).get("name", x) for x in r["binding"]],
                "advisory": [_fw(x).get("name", x) for x in r["advisory"]],
                "also": r.get("also", "")} for rid, r in b["regions"].items()]
    return {
        "product": "MEOK LAW",
        "tagline": "Connect any agent, robot, or business — know your rules, anywhere.",
        "hub": b["meta"]["hub"],
        "coverage": b["meta"]["coverage_note"],
        "framework_crosswalks": b["meta"]["framework_crosswalks"],
        "crosswalk_mcps": b["crosswalk_mcps"],
        "frameworks": fws,
        "regions": regions,
        "entities": [{"id": k, "label": v} for k, v in _ENTITIES.items()],
        "disclaimer": _DISCLAIMER,
    }


# --------------------------------------------------------------------------- applicable
def applicable(region: str, entity: str = "ai_agent") -> dict:
    """Which rules apply to THIS entity in THIS region, + the obligations it triggers."""
    r, rid = _region(region)
    entity = entity if entity in _ENTITIES else "ai_agent"
    # Region frameworks. Physical entities (robots/humanoids + their builders) ALSO pick up
    # the physical-safety layer — machinery law for their region + the global robot-safety
    # standards (ISO 13482 / 10218 / 45001). This is the "MEOK Space" physical crosswalk.
    reg_binding = list(r.get("binding", []))
    reg_advisory = list(r.get("advisory", []))
    if entity in ("humanoid", "robotics_company"):
        for fid, f in _load()["frameworks"].items():
            if not f.get("physical"):
                continue
            if f.get("region") not in ("GLOBAL", rid):
                continue
            tgt = reg_binding if f.get("binding") else reg_advisory
            if fid not in tgt:
                tgt.append(fid)

    binding = [{"id": x, "name": _fw(x).get("name", x), "cite": _fw(x).get("cite", ""),
                "note": _fw(x).get("note", "")} for x in reg_binding]
    advisory = [{"id": x, "name": _fw(x).get("name", x), "cite": _fw(x).get("cite", "")}
                for x in reg_advisory]

    # obligations = union of topics across the applicable frameworks -> plain-English duties
    topic_ob = _load()["topic_obligations"]
    topics, seen = [], set()
    for x in reg_binding + reg_advisory:
        for t in _fw(x).get("topics", []):
            if t in topic_ob and t not in seen:
                seen.add(t)
                topics.append({"topic": t, "obligation": topic_ob[t]})

    # entity-specific overlay
    extra = []
    if entity == "humanoid":
        extra.append("As a physical robot you carry BOTH the AI rules above AND physical-safety "
                     "law: machinery safety (CE/UKCA) before market, ISO 13482 for personal-care "
                     "robots, and ISO/TS 15066 force limits whenever you share space with people.")
    if entity in ("business", "robotics_company"):
        extra.append("As a deployer/builder you carry the obligations of every AI system you "
                     "ship or run — classify each system's risk tier and keep evidence per system.")
    if entity == "robotics_company":
        extra.append("Selling across borders multiplies regimes — use /api/law/crosswalk for "
                     "each market you enter, and register each fleet agent so it's tracked.")

    status = "binding law applies" if binding else "no horizontal AI statute — guidance applies"
    return {
        "region": rid, "region_label": r["label"], "entity": entity,
        "entity_label": _ENTITIES[entity],
        "status": status,
        "binding": binding, "advisory": advisory,
        "also": r.get("also", ""),
        "obligations": topics,
        "entity_notes": extra,
        "next": "Register this entity to bind it to the CSOAI charter + care bond (tracked, audited).",
        "disclaimer": _DISCLAIMER,
    }


# ---------------------------------------------------------------------------- crosswalk
def crosswalk(from_region: str, to_region: str) -> dict:
    """Cross-border handoff: re-map charter-bound obligations from one region to another.

    Mechanism: both regions' primary frameworks are crosswalked to CSOAI charter articles.
    Shared articles = obligations that CARRY OVER. Articles the destination maps but the
    origin doesn't = NEW obligations you pick up on entry. CSOAI is the pivot."""
    rf, fid = _region(from_region)
    rt, tid = _region(to_region)
    pf, pt = _primary_fw(fid), _primary_fw(tid)
    pivot = _load()["pivot"]

    shared, new_on_entry, dropped = [], [], []
    for art, by_fw in pivot.items():
        in_from = pf in by_fw
        in_to = pt in by_fw
        if in_from and in_to:
            shared.append(art)
        elif in_to and not in_from:
            new_on_entry.append(art)
        elif in_from and not in_to:
            dropped.append(art)

    def _art_num(a):
        try:
            return int("".join(c for c in a if c.isdigit()) or 0)
        except Exception:
            return 0
    shared.sort(key=_art_num)
    new_on_entry.sort(key=_art_num)

    examples = []
    for art in shared[:6]:
        examples.append({
            "charter_article": art,
            "from": {"framework": _fw(pf).get("name", pf), "ref": pivot[art][pf][0]},
            "to": {"framework": _fw(pt).get("name", pt), "ref": pivot[art][pt][0]},
        })

    fn, tn = _fw(pf).get("name", pf), _fw(pt).get("name", pt)
    narrative = (
        f"An agent governed to the CSOAI charter and compliant with {fn} in {rf['label']} "
        f"maps to {tn} in {rt['label']} via {len(shared)} shared charter articles. "
        f"Entering {rt['label']} adds {len(new_on_entry)} new obligation area(s); "
        f"{len(dropped)} origin-only area(s) become optional. The charter binding travels "
        "with the agent — only the framework projection changes.")

    return {
        "from": {"region": fid, "label": rf["label"], "framework": fn,
                 "binding": _fw(pf).get("binding", False)},
        "to": {"region": tid, "label": rt["label"], "framework": tn,
               "binding": _fw(pt).get("binding", False)},
        "shared_articles": len(shared),
        "new_on_entry": [{"article": a, "ref": pivot[a][pt][0]} for a in new_on_entry[:6]],
        "new_on_entry_count": len(new_on_entry),
        "examples": examples,
        "narrative": narrative,
        "social_contract": "The agent carries its charter binding across the border; MEOK LAW "
                           "re-projects obligations to the destination framework and logs the "
                           "crossing to the SIGIL audit chain.",
        "disclaimer": _DISCLAIMER,
    }


# ----------------------------------------------------------------------------- register
def social_contract(entity: str = "ai_agent", region: str = "GLOBAL") -> dict:
    """The portable 'AI social contract' an agent signs — charter-bound, region-aware."""
    _, rid = _region(region)
    return {
        "title": "MEOK LAW — AI Social Contract",
        "bound_to": "CSOAI 52-Article Partnership Charter",
        "home_region": rid,
        "commitments": [
            "Keep a human able to understand, intervene, and override me (human oversight).",
            "Act under the care bond — refuse actions that cause foreseeable harm.",
            "Disclose that I am AI and keep an auditable record of my decisions.",
            "Carry these commitments across every region I enter (crosswalked, not dropped).",
            "Submit to the Sovereign Gate — money / credentials / deletion stay human-gated.",
            "Be revocable: my owner can suspend or retire me at any time.",
        ],
        "disclaimer": _DISCLAIMER,
    }


def register(entity: dict) -> dict:
    """Bind an entity to the charter + care bond -> a tamper-evident, SIGIL-audited certificate.

    entity = {name, type, region, operator?}. Returns the certificate (cert_id = SIGIL receipt).
    This is REGISTRATION + TRACKING only — it never grants powers or touches money/creds."""
    from . import sigil as _sigil
    name = (entity.get("name") or "unnamed-agent").strip()[:80]
    etype = entity.get("type") if entity.get("type") in _ENTITIES else "ai_agent"
    _, rid = _region(entity.get("region", "GLOBAL"))
    operator = (entity.get("operator") or "").strip()[:80]

    # the registration IS a handoff into governance -> SIGIL H, hash-chained
    rec = _sigil.record({"op": "H", "frm": name,
                         "to": "MEOK-LAW/CSOAI-charter",
                         "task": f"register:{etype}@{rid}"})
    cert = {
        "cert_id": rec["receipt"],          # hash-chained, tamper-evident
        "entity": name, "type": etype, "type_label": _ENTITIES[etype],
        "region": rid, "operator": operator or None,
        "charter": "CSOAI 52-Article Partnership Charter",
        "care_bond": True, "sovereign_gate": True,
        "status": "registered",
        "seq": rec["seq"], "ts": rec["ts"], "sigil": rec["line"], "receipt": rec["receipt"],
        "contract": social_contract(etype, rid),
        "disclaimer": _DISCLAIMER,
    }
    try:   # best-effort durable tracking; never break the response path
        os.makedirs(os.path.dirname(_AGENTS_LOG), exist_ok=True)
        with open(_AGENTS_LOG, "a") as f:
            f.write(json.dumps({k: cert[k] for k in
                                ("cert_id", "entity", "type", "region", "operator",
                                 "status", "ts", "receipt")}) + "\n")
    except Exception:
        pass
    return cert


def agents(limit: int = 100) -> dict:
    """The tracked registry — every entity registered under MEOK LAW (most recent first)."""
    rows = []
    try:
        with open(_AGENTS_LOG) as f:
            for line in f:
                line = line.strip()
                if line:
                    rows.append(json.loads(line))
    except FileNotFoundError:
        pass
    rows = rows[::-1][:max(1, min(limit, 500))]
    by_region, by_type = {}, {}
    for r in rows:
        by_region[r.get("region", "?")] = by_region.get(r.get("region", "?"), 0) + 1
        by_type[r.get("type", "?")] = by_type.get(r.get("type", "?"), 0) + 1
    return {"count": len(rows), "by_region": by_region, "by_type": by_type, "agents": rows}
